### ISSUE TITLE
16 Reference Images 

### ISSUE THREAD

**Issue by dothuhahb98** [sunwei925/CVIQDatabase#2]
Hello. 
Thank you for your work. 
The CIQA dataset folder includes 544 images. How do I know what are those reference images.

**Comment by sunwei925** [comment]
The images with names from 1*n to 11*n are compressed by JPEG, with names from 12*n to 22*n are compressed by AVC, with names from 23*n to 33*n are compressed by HEVC, and with names 34*n are original images.
